import catSoftToys from "@/assets/cat-soft-toys.jpg";
import catRcToys from "@/assets/cat-rc-toys.jpg";
import catEducational from "@/assets/cat-educational.jpg";
import catActionFigures from "@/assets/cat-action-figures.jpg";
import catCollectibles from "@/assets/cat-collectibles.jpg";
import type { Product } from "./store";

export const categories = [
  { id: "soft-toys", name: "Soft Toys", image: catSoftToys, color: "bg-toy-pink" },
  { id: "rc-toys", name: "RC Toys", image: catRcToys, color: "bg-toy-teal" },
  { id: "educational", name: "Educational", image: catEducational, color: "bg-toy-yellow" },
  { id: "action-figures", name: "Action Figures", image: catActionFigures, color: "bg-toy-purple" },
  { id: "collectibles", name: "Collectibles", image: catCollectibles, color: "bg-toy-orange" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Giant Teddy Bear - Premium Soft",
    price: 1299,
    originalPrice: 1999,
    image: catSoftToys,
    category: "soft-toys",
    rating: 4.8,
    reviewCount: 124,
    badge: "Bestseller",
    inStock: true,
    description: "Super soft and cuddly 3ft giant teddy bear, perfect for gifts and kids.",
  },
  {
    id: "2",
    name: "Turbo RC Racing Car 1:16",
    price: 2499,
    originalPrice: 3499,
    image: catRcToys,
    category: "rc-toys",
    rating: 4.6,
    reviewCount: 89,
    badge: "30% Off",
    inStock: true,
    description: "High-speed remote control racing car with rechargeable battery.",
  },
  {
    id: "3",
    name: "Wooden Building Blocks Set",
    price: 899,
    originalPrice: 1299,
    image: catEducational,
    category: "educational",
    rating: 4.9,
    reviewCount: 203,
    badge: "Top Rated",
    inStock: true,
    description: "100-piece colorful wooden building blocks for creative play.",
  },
  {
    id: "4",
    name: "Ultimate Hero Action Figure",
    price: 1599,
    originalPrice: 2199,
    image: catActionFigures,
    category: "action-figures",
    rating: 4.7,
    reviewCount: 67,
    inStock: true,
    description: "Detailed 12-inch action figure with 20 points of articulation.",
  },
  {
    id: "5",
    name: "Anime Collector's Edition Figure",
    price: 3999,
    originalPrice: 4999,
    image: catCollectibles,
    category: "collectibles",
    rating: 4.9,
    reviewCount: 45,
    badge: "Limited",
    inStock: true,
    description: "Premium hand-painted anime collectible figurine, limited edition.",
  },
  {
    id: "6",
    name: "Cuddly Unicorn Plush",
    price: 799,
    originalPrice: 1099,
    image: catSoftToys,
    category: "soft-toys",
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    description: "Magical rainbow unicorn plush toy, super soft material.",
  },
  {
    id: "7",
    name: "RC Helicopter with Gyro",
    price: 1899,
    originalPrice: 2699,
    image: catRcToys,
    category: "rc-toys",
    rating: 4.4,
    reviewCount: 78,
    badge: "New",
    inStock: true,
    description: "3.5 channel RC helicopter with gyroscope stabilization.",
  },
  {
    id: "8",
    name: "STEM Robot Building Kit",
    price: 2199,
    originalPrice: 2999,
    image: catEducational,
    category: "educational",
    rating: 4.8,
    reviewCount: 92,
    badge: "STEM",
    inStock: true,
    description: "Build your own programmable robot with 300+ pieces.",
  },
];
